# ================== Configuration ==================
name=PropertiesConfig 

# Log directory
property.filename=logs

# ================== Appenders ==================
appenders=console,file

# -------- Console Appender --------
appender.console.type=Console
appender.console.name=CONSOLE
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c - %msg%n

# -------- File Appender --------
appender.file.type=File
appender.file.name=FILE
appender.file.fileName=${filename}/mylog.log
appender.file.layout.type=PatternLayout
appender.file.layout.pattern=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c - %msg%n

# ================== Root Logger ==================

logger.StepDefination.name=StepDefination
logger.StepDefination.level=info
logger.StepDefination.additivity=false
logger.StepDefination.appenderRefs=console,file
logger.StepDefination.appenderRef.file.ref=FILE
logger.StepDefination.appenderRef.console.ref=CONSOLE


